In [ ]:
import pandas as pd
import numpy as np

In [3]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [19]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns= ["Name", "Age", "City", "Salary"]
df2 = pd.DataFrame(data_list, columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [20]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selection and Indexing of Columns

In [23]:
df2[["Name", "City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

Creating a new column

In [24]:
df2["Designation"]=["Dr","Eng", "Unemployed", "Jobless"]
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000          Dr
1   Anna   34     Paris   70000         Eng
2  Peter   29    Berlin   62000  Unemployed
3  Linda   42    London   85000     Jobless

Removing Columns

In [ ]:
df2.drop(["City","Designation"], axis=1) # use "Inplace=True" if you want to remove it permanently

    Name  Age  Salary
0   John   28   65000
1   Anna   34   70000
2  Peter   29   62000
3  Linda   42   85000

In [41]:
df2.drop(0, axis=0)

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000         Eng
2  Peter   29  Berlin   62000  Unemployed
3  Linda   42  London   85000     Jobless

Selecting Rows

In [43]:
df2.loc[[0,1]]

   Name  Age      City  Salary Designation
0  John   28  New York   65000          Dr
1  Anna   34     Paris   70000         Eng

In [45]:
df2.iloc[3]

Name             Linda
Age                 42
City            London
Salary           85000
Designation    Jobless
Name: 3, dtype: object

Selecting Subsets of Rows and Columns

In [46]:
df2.loc[[0,1]][["Name", "Salary"]]

   Name  Salary
0  John   65000
1  Anna   70000

conditional data

In [47]:
#I only want to see those people whose age is above 30

In [48]:
df2[df2["Age"] > 30]

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000         Eng
3  Linda   42  London   85000     Jobless

In [51]:
df2[(df2["Age"]>30) & (df2["Salary"]>70000)]

    Name  Age    City  Salary Designation
3  Linda   42  London   85000     Jobless